        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      reset 		; Reset     ; Int 08h (IRQ 0)
        dd      tick 		; Tick      ; Int 09h (IRQ 1)
        dd      keyboard 	; Keyboard  ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)

	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)

	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)

	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)

	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84
reset:
	mov ax, 0
	push ax
	call exit
tick:
	push AX
	push BX
	push CX
	push DX
	push BP
	push SI
	push DI
	push DS
	push ES

    call YKEnterISR
	sti
	call lab6tick
	cli
    call YKExitISR

	mov al, 0x20
	out 0x20, al
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX
	iret
keyboard:
	push AX
	push BX
	push CX
	push DX
	push BP
	push SI
	push DI
	push DS
	push ES

    call YKEnterISR

	sti
	call lab6keybrd
	cli

    call YKExitISR

	mov al, 0x20
	out 0x20, al
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX
	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab6inth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
lab6reset:
	jmp	L_lab6inth_1
L_lab6inth_2:
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_lab6inth_1:
	push	bp
	mov	bp, sp
	jmp	L_lab6inth_2
	ALIGN	2
L_lab6inth_4:
	DW	0
L_lab6inth_5:
	DW	0
L_lab6inth_6:
	DB	"  TickISR: queue overflow! ",0xA,0
	ALIGN	2
lab6tick:
	jmp	L_lab6inth_7
L_lab6inth_8:
	call	YKTickHandler
	mov	ax, word [L_lab6inth_4]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, MsgArray
	mov	ax, word [YKTickNum]
	mov	word [si], ax
	mov	ax, word [L_lab6inth_5]
	add	ax, 89
	cwd
	mov	cx, 100
	idiv	cx
	mov	ax, dx
	mov	word [L_lab6inth_5], ax
	mov	ax, word [L_lab6inth_4]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	mov	si, ax
	add	si, 2
	mov	ax, word [L_lab6inth_5]
	mov	word [si], ax
	mov	ax, word [L_lab6inth_4]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	push	ax
	push	word [MsgQPtr]
	call	YKQPost
	add	sp, 4
	test	ax, ax
	jne	L_lab6inth_9
	mov	ax, L_lab6inth_6
	push	ax
	call	printString
	add	sp, 2
	jmp	L_lab6inth_10
L_lab6inth_9:
	mov	ax, word [L_lab6inth_4]
	inc	ax
	mov	word [L_lab6inth_4], ax
	cmp	ax, 20
	jl	L_lab6inth_11
	mov	word [L_lab6inth_4], 0
L_lab6inth_11:
L_lab6inth_10:
	mov	sp, bp
	pop	bp
	ret
L_lab6inth_7:
	push	bp
	mov	bp, sp
	jmp	L_lab6inth_8
	ALIGN	2
lab6keybrd:
	jmp	L_lab6inth_13
L_lab6inth_14:
	mov	word [GlobalFlag], 1
	mov	sp, bp
	pop	bp
	ret
L_lab6inth_13:
	push	bp
	mov	bp, sp
	jmp	L_lab6inth_14
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKSemAvailCount:
	DW	12
YKQAvailCount:
	DW	24
	ALIGN	2
queue_insertNode:
	jmp	L_yakc_1
L_yakc_2:
	mov	si, word [bp+4]
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_3
	mov	ax, word [bp+6]
	mov	word [si], ax
	mov	si, word [bp+6]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakc_4
L_yakc_3:
	mov	si, word [bp+6]
	add	si, 6
	mov	di, word [bp+4]
	mov	di, word [di]
	add	di, 6
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_5
	mov	si, word [bp+4]
	mov	di, word [bp+6]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	mov	si, word [bp+4]
	mov	ax, word [bp+6]
	mov	word [si], ax
	jmp	L_yakc_4
L_yakc_5:
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	jmp	L_yakc_7
L_yakc_6:
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_7:
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_9
	mov	si, word [bp-2]
	add	si, 10
	mov	si, word [si]
	add	si, 6
	mov	di, word [bp+6]
	add	di, 6
	mov	ax, word [di]
	cmp	ax, word [si]
	jge	L_yakc_6
L_yakc_9:
L_yakc_8:
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp+6]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
L_yakc_4:
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
queue_pop:
	jmp	L_yakc_11
L_yakc_12:
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	mov	si, word [bp+4]
	mov	si, word [si]
	add	si, 10
	mov	di, word [bp+4]
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
L_yakc_13:
	mov	sp, bp
	pop	bp
	ret
L_yakc_11:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_12
L_yakc_15:
	DB	"Task: ",0
	ALIGN	2
printQueue:
	jmp	L_yakc_16
L_yakc_17:
	jmp	L_yakc_19
L_yakc_18:
	mov	ax, L_yakc_15
	push	ax
	call	printString
	add	sp, 2
	mov	si, word [bp+4]
	add	si, 14
	push	word [si]
	call	printInt
	add	sp, 2
	mov	al, 32
	push	ax
	call	printChar
	add	sp, 2
	mov	si, word [bp+4]
	add	si, 6
	push	word [si]
	call	printInt
	add	sp, 2
	call	printNewLine
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp+4], ax
L_yakc_19:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_18
L_yakc_20:
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKScheduler:
	jmp	L_yakc_22
L_yakc_23:
	call	YKEnterMutex
	mov	ax, word [RunningTask]
	cmp	ax, word [YKRdyList]
	jne	L_yakc_24
	call	YKExitMutex
	jmp	L_yakc_25
L_yakc_24:
	mov	ax, word [RunningTask]
	mov	word [TaskToSave], ax
	mov	ax, word [YKRdyList]
	mov	word [RunningTask], ax
	inc	word [YKCtxSwCount]
	mov	ax, 1
	push	ax
	call	YKDispatcher
	add	sp, 2
L_yakc_25:
	mov	sp, bp
	pop	bp
	ret
L_yakc_22:
	push	bp
	mov	bp, sp
	jmp	L_yakc_23
	ALIGN	2
YKIdleTask:
	jmp	L_yakc_27
L_yakc_28:
	jmp	L_yakc_30
L_yakc_29:
	call	YKEnterMutex
	inc	word [YKIdleCount]
	call	YKExitMutex
L_yakc_30:
	jmp	L_yakc_29
L_yakc_31:
	mov	sp, bp
	pop	bp
	ret
L_yakc_27:
	push	bp
	mov	bp, sp
	jmp	L_yakc_28
	ALIGN	2
L_yakc_33:
	DW	0
L_yakc_34:
	DB	"Creating Task: ",0
	ALIGN	2
YKNewTask:
	jmp	L_yakc_35
L_yakc_36:
	call	YKEnterMutex
	mov	ax, word [bp+6]
	sub	ax, 2
	mov	word [bp-6], ax
	sub	word [bp-6], 2
	mov	si, word [bp-6]
	mov	word [si], 0
	sub	word [bp-6], 2
	mov	si, word [bp-6]
	mov	ax, word [bp+4]
	mov	word [si], ax
	sub	word [bp-6], 2
	mov	ax, word [bp+6]
	dec	ax
	mov	si, word [bp-6]
	mov	word [si], ax
	mov	word [bp-4], 0
	jmp	L_yakc_38
L_yakc_37:
	sub	word [bp-6], 2
	mov	si, word [bp-6]
	mov	word [si], 0
L_yakc_40:
	inc	word [bp-4]
L_yakc_38:
	cmp	word [bp-4], 8
	jl	L_yakc_37
L_yakc_39:
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	mov	si, word [YKAvailTCBList]
	add	si, 10
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	mov	si, word [bp-2]
	mov	ax, word [bp-6]
	mov	word [si], ax
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], ax
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	mov	ax, L_yakc_34
	push	ax
	call	printString
	add	sp, 2
	push	word [L_yakc_33]
	call	printInt
	add	sp, 2
	call	printNewLine
	mov	ax, word [L_yakc_33]
	inc	word [L_yakc_33]
	mov	si, word [bp-2]
	add	si, 14
	mov	word [si], ax
	push	word [bp-2]
	mov	ax, YKRdyList
	push	ax
	call	queue_insertNode
	add	sp, 4
	mov	ax, word [Running]
	test	ax, ax
	je	L_yakc_41
	call	YKScheduler
L_yakc_41:
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_35:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_36
	ALIGN	2
YKInitialize:
	jmp	L_yakc_43
L_yakc_44:
	mov	word [Running], 0
	mov	word [YKIdleCount], 0
	mov	word [YKCtxSwCount], 0
	mov	word [YKTickNum], 0
	mov	word [NestingLevel], 0
	mov	word [YKSuspList], 0
	mov	word [YKAvailTCBList], YKTCBArray
	mov	word [bp-2], 0
	jmp	L_yakc_46
L_yakc_45:
	mov	ax, word [bp-2]
	inc	ax
	mov	cx, 4
	shl	ax, cl
	add	ax, YKTCBArray
	mov	dx, word [bp-2]
	mov	cx, 4
	shl	dx, cl
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 10
	mov	word [si], ax
L_yakc_48:
	inc	word [bp-2]
L_yakc_46:
	cmp	word [bp-2], 5
	jl	L_yakc_45
L_yakc_47:
	mov	word [(90+YKTCBArray)], 0
	mov	al, 100
	push	ax
	mov	ax, (IdleStk+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	ax, word [YKRdyList]
	mov	word [RunningTask], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_43:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_44
	ALIGN	2
YKRun:
	jmp	L_yakc_50
L_yakc_51:
	mov	word [Running], 1
	inc	word [YKCtxSwCount]
	mov	ax, word [YKRdyList]
	mov	word [RunningTask], ax
	xor	ax, ax
	push	ax
	call	YKDispatcher
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_50:
	push	bp
	mov	bp, sp
	jmp	L_yakc_51
	ALIGN	2
YKDelayTask:
	jmp	L_yakc_53
L_yakc_54:
	call	YKEnterMutex
	mov	ax, YKRdyList
	push	ax
	call	queue_pop
	add	sp, 2
	mov	word [bp-2], ax
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	mov	si, word [bp-2]
	add	si, 12
	mov	word [si], 0
	mov	ax, word [YKSuspList]
	test	ax, ax
	je	L_yakc_55
	mov	si, word [YKSuspList]
	add	si, 12
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_55:
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [YKSuspList]
	mov	word [si], ax
	mov	ax, word [bp-2]
	mov	word [YKSuspList], ax
	call	YKScheduler
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_53:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_54
	ALIGN	2
YKTickHandler:
	jmp	L_yakc_57
L_yakc_58:
	call	YKEnterMutex
	inc	word [YKTickNum]
	mov	ax, word [YKSuspList]
	mov	word [bp-2], ax
	jmp	L_yakc_60
L_yakc_59:
	mov	si, word [bp-2]
	add	si, 8
	dec	word [si]
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_62
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-4], ax
	mov	si, word [bp-2]
	add	si, 12
	mov	di, word [bp-4]
	add	di, 12
	mov	ax, word [si]
	mov	word [di], ax
	mov	si, word [bp-2]
	add	si, 12
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	push	word [bp-2]
	mov	ax, YKRdyList
	push	ax
	call	queue_insertNode
	add	sp, 4
	mov	ax, word [YKSuspList]
	cmp	ax, word [bp-2]
	jne	L_yakc_63
	mov	ax, word [bp-4]
	mov	word [YKSuspList], ax
L_yakc_63:
	mov	ax, word [bp-4]
	mov	word [bp-2], ax
	jmp	L_yakc_64
L_yakc_62:
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_64:
L_yakc_60:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_59
L_yakc_61:
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_57:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_58
	ALIGN	2
YKEnterISR:
	jmp	L_yakc_66
L_yakc_67:
	inc	word [NestingLevel]
	mov	sp, bp
	pop	bp
	ret
L_yakc_66:
	push	bp
	mov	bp, sp
	jmp	L_yakc_67
	ALIGN	2
YKExitISR:
	jmp	L_yakc_69
L_yakc_70:
	dec	word [NestingLevel]
	mov	ax, word [NestingLevel]
	test	ax, ax
	jne	L_yakc_71
	mov	ax, word [Running]
	test	ax, ax
	je	L_yakc_71
	call	YKScheduler
L_yakc_71:
	mov	sp, bp
	pop	bp
	ret
L_yakc_69:
	push	bp
	mov	bp, sp
	jmp	L_yakc_70
L_yakc_73:
	DB	"Not enough semaphores",0
	ALIGN	2
YKSemCreate:
	jmp	L_yakc_74
L_yakc_75:
	call	YKEnterMutex
	mov	ax, word [YKSemAvailCount]
	test	ax, ax
	jne	L_yakc_76
	call	YKExitMutex
	mov	ax, L_yakc_73
	push	ax
	call	printString
	add	sp, 2
	mov	al, 255
	push	ax
	call	exit
	add	sp, 2
L_yakc_76:
	dec	word [YKSemAvailCount]
	mov	ax, word [YKSemAvailCount]
	shl	ax, 1
	shl	ax, 1
	add	ax, YKSemaphores
	mov	word [bp-2], ax
	mov	si, word [bp-2]
	mov	ax, word [bp+4]
	mov	word [si], ax
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	call	YKExitMutex
	mov	ax, word [bp-2]
L_yakc_77:
	mov	sp, bp
	pop	bp
	ret
L_yakc_74:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_75
	ALIGN	2
YKSemPend:
	jmp	L_yakc_79
L_yakc_80:
	call	YKEnterMutex
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	word [si]
	test	ax, ax
	jle	L_yakc_81
	call	YKExitMutex
	jmp	L_yakc_82
L_yakc_81:
	mov	ax, YKRdyList
	push	ax
	call	queue_pop
	add	sp, 2
	mov	word [bp-2], ax
	push	word [bp-2]
	mov	ax, word [bp+4]
	add	ax, 2
	push	ax
	call	queue_insertNode
	add	sp, 4
	call	YKScheduler
	call	YKExitMutex
L_yakc_82:
	mov	sp, bp
	pop	bp
	ret
L_yakc_79:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_80
	ALIGN	2
YKSemPost:
	jmp	L_yakc_84
L_yakc_85:
	call	YKEnterMutex
	mov	si, word [bp+4]
	mov	ax, word [si]
	inc	word [si]
	test	ax, ax
	jl	L_yakc_86
	call	YKExitMutex
	jmp	L_yakc_87
L_yakc_86:
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_88
	mov	ax, word [bp+4]
	add	ax, 2
	push	ax
	call	queue_pop
	add	sp, 2
	mov	word [bp-2], ax
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp+4]
	add	di, 2
	mov	ax, word [si]
	mov	word [di], ax
	push	word [bp-2]
	mov	ax, YKRdyList
	push	ax
	call	queue_insertNode
	add	sp, 4
	mov	ax, word [NestingLevel]
	test	ax, ax
	jne	L_yakc_89
	call	YKScheduler
L_yakc_89:
L_yakc_88:
	call	YKExitMutex
L_yakc_87:
	mov	sp, bp
	pop	bp
	ret
L_yakc_84:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_85
L_yakc_91:
	DB	"Too many message queues created. Allocate more space",0xA,0
	ALIGN	2
YKQCreate:
	jmp	L_yakc_92
L_yakc_93:
	call	YKEnterMutex
	mov	ax, word [YKQAvailCount]
	test	ax, ax
	jne	L_yakc_94
	call	YKExitMutex
	mov	ax, L_yakc_91
	push	ax
	call	printString
	add	sp, 2
	mov	al, 255
	push	ax
	call	exit
	add	sp, 2
L_yakc_94:
	dec	word [YKQAvailCount]
	mov	ax, word [YKQAvailCount]
	mov	cx, 12
	imul	cx
	add	ax, YKQueues
	mov	word [bp-2], ax
	mov	si, word [bp-2]
	mov	ax, word [bp+4]
	mov	word [si], ax
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp+6]
	mov	word [si], ax
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], 0
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	call	YKExitMutex
	mov	ax, word [bp-2]
L_yakc_95:
	mov	sp, bp
	pop	bp
	ret
L_yakc_92:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_93
	ALIGN	2
YKQPend:
	jmp	L_yakc_97
L_yakc_98:
	call	YKEnterMutex
	mov	si, word [bp+4]
	add	si, 10
	cmp	word [si], 0
	jg	L_yakc_99
	mov	ax, YKRdyList
	push	ax
	call	queue_pop
	add	sp, 2
	mov	word [bp-4], ax
	push	word [bp-4]
	mov	ax, word [bp+4]
	add	ax, 8
	push	ax
	call	queue_insertNode
	add	sp, 4
	call	YKScheduler
L_yakc_99:
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	inc	word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-2], ax
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	add	di, 2
	mov	ax, word [di]
	cmp	ax, word [si]
	ja	L_yakc_100
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_100:
	mov	si, word [bp+4]
	add	si, 10
	dec	word [si]
	call	YKExitMutex
	mov	ax, word [bp-2]
L_yakc_101:
	mov	sp, bp
	pop	bp
	ret
L_yakc_97:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_98
	ALIGN	2
YKQPost:
	jmp	L_yakc_103
L_yakc_104:
	call	YKEnterMutex
	mov	si, word [bp+4]
	add	si, 10
	mov	di, word [bp+4]
	add	di, 2
	mov	ax, word [di]
	cmp	ax, word [si]
	ja	L_yakc_105
	call	YKExitMutex
	xor	ax, ax
	jmp	L_yakc_106
L_yakc_105:
	mov	si, word [bp+4]
	add	si, 10
	inc	word [si]
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	inc	word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	mov	si, word [bp+4]
	add	si, 4
	mov	di, word [bp+4]
	add	di, 2
	mov	ax, word [di]
	cmp	ax, word [si]
	ja	L_yakc_107
	mov	si, word [bp+4]
	add	si, 4
	mov	word [si], 0
L_yakc_107:
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_108
	mov	ax, word [bp+4]
	add	ax, 8
	push	ax
	call	queue_pop
	add	sp, 2
	mov	word [bp-2], ax
	push	word [bp-2]
	mov	ax, YKRdyList
	push	ax
	call	queue_insertNode
	add	sp, 4
	mov	ax, word [NestingLevel]
	test	ax, ax
	jne	L_yakc_109
	call	YKScheduler
L_yakc_109:
L_yakc_108:
	call	YKExitMutex
	mov	ax, 1
L_yakc_106:
	mov	sp, bp
	pop	bp
	ret
L_yakc_103:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_104
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
Running:
	TIMES	2 db 0
TaskToSave:
	TIMES	2 db 0
RunningTask:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKSuspList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	96 db 0
IdleStk:
	TIMES	512 db 0
NestingLevel:
	TIMES	2 db 0
YKSemaphores:
	TIMES	48 db 0
YKQueues:
	TIMES	288 db 0
YKEnterMutex:
    cli
    ret

YKExitMutex:
    sti
    ret

YKSaveContext:
    pushf           ; Saving Flags
    push cs         ; Code Segment
    push word[bp+2] ; Instruction Pointer

    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    push es
    push ds

    mov bx, [TaskToSave]
    mov [bx], sp

    jmp YKRestoreContext

YKDispatcher:
    push bp
    mov bp, sp
    push ax
    mov ax, word[bp+4]
    cmp al, 1
    pop ax
    je YKSaveContext
YKRestoreContext:
    mov bx, [RunningTask]
    mov sp, [bx]

    pop ds
    pop es
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    iret    ; Restores Flags, Code Segment, and the Instruction Pointer.

YKTick:
    ;Save Context
    push AX
    push BX
    push CX
    push DX
    push BP
    push SI
    push DI
    push DS
    push ES

    call YKEnterISR

    sti
    call YKTickHandler
    cli

    call YKExitISR

    mov al, 0x20
    out 0x20, al
    pop ES
    pop DS
    pop DI
    pop SI
    pop BP
    pop DX
    pop CX
    pop BX
    pop AX
    iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab6_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab6_app_5:
	DB	"Max: ",0
L_lab6_app_4:
	DB	"Min: ",0
L_lab6_app_3:
	DB	0x9,0
L_lab6_app_2:
	DB	"Ticks: ",0
L_lab6_app_1:
	DB	"! Dropped msgs: tick ",0
	ALIGN	2
ATask:
	jmp	L_lab6_app_6
L_lab6_app_7:
	mov	word [bp-4], 100
	mov	word [bp-6], 0
	mov	word [bp-8], 0
	jmp	L_lab6_app_9
L_lab6_app_8:
	push	word [MsgQPtr]
	call	YKQPend
	add	sp, 2
	mov	word [bp-2], ax
	mov	ax, word [bp-8]
	inc	ax
	mov	si, word [bp-2]
	mov	dx, word [si]
	cmp	dx, ax
	je	L_lab6_app_11
	mov	ax, 21
	push	ax
	mov	ax, L_lab6_app_1
	push	ax
	call	print
	add	sp, 4
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, word [bp-8]
	dec	ax
	cmp	ax, 1
	jle	L_lab6_app_12
	mov	ax, word [bp-8]
	inc	ax
	push	ax
	call	printInt
	add	sp, 2
	mov	al, 45
	push	ax
	call	printChar
	add	sp, 2
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	call	printNewLine
	jmp	L_lab6_app_13
L_lab6_app_12:
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	call	printNewLine
L_lab6_app_13:
L_lab6_app_11:
	mov	si, word [bp-2]
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jle	L_lab6_app_14
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-4], ax
L_lab6_app_14:
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-6]
	cmp	ax, word [si]
	jge	L_lab6_app_15
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-6], ax
L_lab6_app_15:
	mov	ax, 7
	push	ax
	mov	ax, L_lab6_app_2
	push	ax
	call	print
	add	sp, 4
	push	word [bp-8]
	call	printInt
	add	sp, 2
	mov	ax, 1
	push	ax
	mov	ax, L_lab6_app_3
	push	ax
	call	print
	add	sp, 4
	mov	ax, 5
	push	ax
	mov	ax, L_lab6_app_4
	push	ax
	call	print
	add	sp, 4
	push	word [bp-4]
	call	printInt
	add	sp, 2
	mov	ax, 1
	push	ax
	mov	ax, L_lab6_app_3
	push	ax
	call	print
	add	sp, 4
	mov	ax, 5
	push	ax
	mov	ax, L_lab6_app_5
	push	ax
	call	print
	add	sp, 4
	push	word [bp-6]
	call	printInt
	add	sp, 2
	call	printNewLine
L_lab6_app_9:
	jmp	L_lab6_app_8
L_lab6_app_10:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_6:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6_app_7
L_lab6_app_17:
	DB	"This is sparta!",0
	ALIGN	2
BTask:
	jmp	L_lab6_app_18
L_lab6_app_19:
	mov	word [bp-4], 1001
	mov	word [bp-10], 0
	jmp	L_lab6_app_21
L_lab6_app_20:
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	cmp	word [GlobalFlag], 1
	jne	L_lab6_app_23
	call	YKEnterMutex
	mov	ax, word [YKTickNum]
	mov	word [bp-2], ax
	call	YKExitMutex
	jmp	L_lab6_app_25
L_lab6_app_24:
	call	YKEnterMutex
	mov	ax, word [YKTickNum]
	mov	word [bp-12], ax
	mov	ax, word [bp-2]
	add	ax, 5
	mov	dx, word [bp-12]
	cmp	dx, ax
	jae	L_lab6_app_26
L_lab6_app_27:
	add	word [bp-4], 2
	mov	word [bp-8], 0
	mov	word [bp-6], 3
	jmp	L_lab6_app_29
L_lab6_app_28:
	mov	ax, word [bp-4]
	cwd
	idiv	word [bp-6]
	mov	ax, dx
	test	ax, ax
	jne	L_lab6_app_32
	mov	word [bp-8], 1
	jmp	L_lab6_app_30
L_lab6_app_32:
L_lab6_app_31:
	add	word [bp-6], 2
L_lab6_app_29:
	mov	ax, word [bp-6]
	imul	word [bp-6]
	mov	dx, word [bp-4]
	cmp	dx, ax
	jg	L_lab6_app_28
L_lab6_app_30:
	mov	ax, word [bp-8]
	test	ax, ax
	jne	L_lab6_app_33
	mov	al, 46
	push	ax
	call	printChar
	add	sp, 2
	mov	ax, word [bp-10]
	inc	ax
	mov	word [bp-10], ax
	cmp	ax, 75
	jle	L_lab6_app_34
	call	printNewLine
	mov	word [bp-10], 0
L_lab6_app_34:
L_lab6_app_33:
L_lab6_app_25:
	jmp	L_lab6_app_24
L_lab6_app_26:
	mov	ax, L_lab6_app_17
	push	ax
	call	printString
	add	sp, 2
	call	printNewLine
	mov	word [bp-10], 0
	mov	word [GlobalFlag], 0
L_lab6_app_23:
L_lab6_app_21:
	jmp	L_lab6_app_20
L_lab6_app_22:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_18:
	push	bp
	mov	bp, sp
	sub	sp, 12
	jmp	L_lab6_app_19
L_lab6_app_40:
	DB	"% >>>>>",0xD,0xA,0
L_lab6_app_39:
	DB	", CPU usage: ",0
L_lab6_app_38:
	DB	"<<<<< Context switches: ",0
L_lab6_app_37:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab6_app_36:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
STask:
	jmp	L_lab6_app_41
L_lab6_app_42:
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	ax, L_lab6_app_36
	push	ax
	call	printString
	add	sp, 2
	mov	ax, L_lab6_app_37
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	word [YKIdleCount], 0
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	mov	word [YKIdleCount], 0
	mov	al, 10
	push	ax
	mov	ax, (BTaskStk+1024)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	al, 20
	push	ax
	mov	ax, (ATaskStk+1024)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	jmp	L_lab6_app_44
L_lab6_app_43:
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	call	YKEnterMutex
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	call	YKExitMutex
	mov	ax, L_lab6_app_38
	push	ax
	call	printString
	add	sp, 2
	push	word [bp-4]
	call	printInt
	add	sp, 2
	mov	ax, L_lab6_app_39
	push	ax
	call	printString
	add	sp, 2
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	mov	ax, L_lab6_app_40
	push	ax
	call	printString
	add	sp, 2
	call	YKEnterMutex
	mov	word [YKCtxSwCount], 0
	mov	word [YKIdleCount], 0
	call	YKExitMutex
L_lab6_app_44:
	jmp	L_lab6_app_43
L_lab6_app_45:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_41:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6_app_42
	ALIGN	2
main:
	jmp	L_lab6_app_47
L_lab6_app_48:
	call	YKInitialize
	mov	word [GlobalFlag], 0
	mov	ax, 10
	push	ax
	mov	ax, MsgQ
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [MsgQPtr], ax
	mov	al, 30
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_47:
	push	bp
	mov	bp, sp
	jmp	L_lab6_app_48
	ALIGN	2
MsgArray:
	TIMES	80 db 0
ATaskStk:
	TIMES	1024 db 0
BTaskStk:
	TIMES	1024 db 0
STaskStk:
	TIMES	1024 db 0
GlobalFlag:
	TIMES	2 db 0
MsgQ:
	TIMES	20 db 0
MsgQPtr:
	TIMES	2 db 0
